<?php

namespace AppBundle\Repository;

/**
 * agent_cargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agent_cargoRepository extends \Doctrine\ORM\EntityRepository
{
}
