<?php

namespace AppBundle\Repository;

/**
 * Air_FreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Air_FreightRepository extends \Doctrine\ORM\EntityRepository
{
}
