<?php

namespace AppBundle\Repository;

/**
 * AirFreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirFreightRepository extends \Doctrine\ORM\EntityRepository
{
}
