<?php

namespace AppBundle\Repository;

/**
 * cargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cargoRepository extends \Doctrine\ORM\EntityRepository
{
}
