<?php

namespace AppBundle\Repository;

/**
 * customercargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class customercargoRepository extends \Doctrine\ORM\EntityRepository
{
}
