<?php

namespace AppBundle\Repository;

/**
 * DinlankaUpbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinlankaUpbRepository extends \Doctrine\ORM\EntityRepository
{
}
