<?php

namespace AppBundle\Repository;

/**
 * DinLankaSeaFreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinLankaSeaFreightRepository extends \Doctrine\ORM\EntityRepository
{
}
