<?php

namespace AppBundle\Repository;

/**
 * Dinlanka_air_freightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dinlanka_air_freightRepository extends \Doctrine\ORM\EntityRepository
{
}
