<?php

namespace AppBundle\Repository;

/**
 * DinLankaAirFreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinLankaAirFreightRepository extends \Doctrine\ORM\EntityRepository
{
}
