<?php

namespace AppBundle\Repository;

/**
 * InvoiceMapping_AirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceMapping_AirRepository extends \Doctrine\ORM\EntityRepository
{
}
