<?php

namespace AppBundle\Repository;

/**
 * InvoiceMapping_SeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceMapping_SeaRepository extends \Doctrine\ORM\EntityRepository
{
}
