<?php

namespace AppBundle\Repository;

/**
 * Sea_FreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sea_FreightRepository extends \Doctrine\ORM\EntityRepository
{
}
