<?php

namespace AppBundle\Repository;

/**
 * SeaFreightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeaFreightRepository extends \Doctrine\ORM\EntityRepository
{
}
