<?php

namespace AppBundle\Repository;

/**
 * UpbCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpbCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
