<?php

namespace AppBundle\Repository;

/**
 * upbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class upbRepository extends \Doctrine\ORM\EntityRepository
{
}
