<?php

namespace AppBundle\Repository;

/**
 * UPBRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UPBRepository extends \Doctrine\ORM\EntityRepository
{
}
