<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4hxa7xl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4hxa7xl/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4hxa7xl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4hxa7xl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4hxa7xl\appProdProjectContainer(array(
    'container.build_hash' => '4hxa7xl',
    'container.build_id' => 'd3e29e53',
    'container.build_time' => 1523429162,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4hxa7xl');
