<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPncfu0e\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPncfu0e/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPncfu0e.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPncfu0e\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPncfu0e\appProdProjectContainer(array(
    'container.build_hash' => 'Pncfu0e',
    'container.build_id' => '8db7dccb',
    'container.build_time' => 1524408571,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPncfu0e');
