<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRety3la\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRety3la/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRety3la.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRety3la\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRety3la\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rety3la',
    'container.build_id' => '4059abaa',
    'container.build_time' => 1525005385,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRety3la');
