<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6bv2f3e\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6bv2f3e/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6bv2f3e.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6bv2f3e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6bv2f3e\appDevDebugProjectContainer(array(
    'container.build_hash' => '6bv2f3e',
    'container.build_id' => '8e6da7a7',
    'container.build_time' => 1525336704,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6bv2f3e');
